### ISSUE TITLE
How to implement in java project?

### ISSUE THREAD

**Issue by moisoni97** [sofakingforever/animated-stars-android#2]
I have tried this to implement your libray in my java project and didn't worked. What am I doing wrong?
`AnimatedStarsView stars_white, stars;`
`stars_white = findViewById(R.id.stars_white);
        stars = findViewById(R.id.stars);`

`stars_white.onStop();
        stars.onStop();`

Error:
`Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #11: Error inflating class com.sofakingforever.stars.AnimatedStarsView`

**Comment by moisoni97** [comment]
I solved it by adding `implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.2.71'` to my `dependencies` !

`@Override`
    `protected void onStart() {`
      ` super.onStart();`
     ` AnimatedStarsView stars = findViewById(R.id.stars);`
      `stars.onStart();`
      `AnimatedStarsView stars_white = findViewById(R.id.stars_white);`
      `stars_white.onStart();`
   ` }`

Hope this will help somebody!

**Comment by xo-pixels** [comment]
Thanks moisoni97!
